version: '3.8'

services:

  web:
    image: php:8.3-apache
    container_name: php-apache-container-cogip
    ports:
      - "5000:80"
    volumes:
      - .:/var/www/html
    networks:
      - my-network
    command: 
      - "bash"
      - "-c"
      - "docker-php-ext-install pdo pdo_mysql && a2enmod rewrite && apache2-foreground"

  mysql:
    image: mysql:8.0
    container_name: mysql-container-cogip
    ports:
      - "5003:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container-cogip
    ports:
      - "5002:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  my-network:

